### ISSUE TITLE
Allow exporting the result as graph in JSON format for better machine to machine interaction

### ISSUE THREAD

**Issue by REASY** [messense/lddtree-rs#7]

**Comment by messense** [comment]
Do you have a real world use case for this?

**Comment by REASY** [comment]
@messense from time to time I need to make a native library available in Java through JNI. For that I have to analyze all the dependencies and their order of load (build DAG and run topological sort).
(here is the app I built on top of your library, https://github.com/REASY/lddtopo-rs/blob/main/src/main.rs)

**Comment by messense** [comment]
Closing as complete now that you have implemented it in `lddtopo-rs`.
